<a href="https://colab.research.google.com/github/Pinedah/ESCOM_development-of-applications-for-data-analysis/blob/main/Practica7_1_4AM1_PHF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Desarrollo de Aplicaciones para Análisis de Datos
-------------------------------------------------
## Práctica 7. Bibliotecas Python

### Nombre: Pineda Hernández Francisco

# NumPy Ejercicios

Ahora que hemos aprendido sobre NumPy vamos a poner a prueba tus conocimientos. Empezaremos con algunas tareas sencillas, y luego se te harán algunas preguntas más complicadas.

#### Importar NumPy como np

In [ ]:
import numpy as np

#### Crear un array de 10 ceros

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Crear un array de 10 unos

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Crear un array de 10 cincos

In [ ]:
np.array([5 for _ in range(10)])

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Crear un array de enteros entre 10 y 50

In [ ]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Crear un array de todos los números enteros pares de 10 a 50

In [ ]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Crear una matriz 3x3 con valores comprendidos entre 0 y 8

In [ ]:
np.arange(0, 9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Crear una matriz indentidad 3x3

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Usa NumPy para generar un número aleatorio entre  0 y 1

In [ ]:
np.random.rand()

0.8672889559715881

#### Utiliza NumPy para generar una matriz de 25 números aleatorios extraídos de una distribución normal estándar.

In [ ]:
# normal(media, desviación estandar, cantidad)
np.random.normal(5, 10, 25).reshape(5,5)

array([[ 3.02686390e+01, -6.85963917e+00, -8.34276545e+00,
         1.16314005e+01,  2.51705710e+01],
       [ 7.55696990e+00,  1.68048625e+00,  2.94162104e+00,
        -2.33971463e-02, -7.84742893e+00],
       [-6.19336275e+00,  1.58775697e+01,  8.27982475e-01,
        -1.15022317e+01,  3.63205319e+00],
       [ 1.35316676e+00, -9.84127894e+00,  7.85133420e+00,
         1.62191509e+01,  3.18128272e+00],
       [ 4.06274624e+00,  6.01471036e+00,  4.93475477e+00,
        -1.11434065e+01,  9.47588066e+00]])

#### Crea una matriz de 20 puntos linealmente espaciados entre 0 y 1:

In [ ]:
np.linspace(0, 1, 20).reshape(4,5)

array([[0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632],
       [0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421],
       [0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211],
       [0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ]])

## Indexación y selección en Numpy

Ahora se te darán unas cuantas matrices, debes replicar las salidas matriciales resultantes:

In [ ]:
matriz = np.arange(1,26).reshape(5,5)
matriz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
matriz[2: , 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
matriz[3,4]

20

In [ ]:
matriz[0:3, 1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [ ]:
matriz[-1, :]

array([21, 22, 23, 24, 25])

In [ ]:
matriz[-2:, :]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Ahora haz lo siguiente

#### Obtener la suma de todos los valores en mat

In [ ]:
np.sum(matriz)

325

####  Obtener la desviación estándar de los valores en mat

In [ ]:
np.std(matriz)

7.211102550927978

#### Obtener la suma de todas las columnas de mat

In [ ]:
np.array([np.sum(matriz[:, 0]), np.sum(matriz[:, 1]), np.sum(matriz[:, 2]), np.sum(matriz[:, 3]), np.sum(matriz[:, 4])])

array([55, 60, 65, 70, 75])